language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo add-apt-repository ppa:biometrics/bob
  - sudo apt-get update -qq
  - sudo apt-get install -qq bob-dev
install:
  - "python bootstrap.py"
  - "./bin/buildout"
script:
  - "./bin/nosetests -sv"
