language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
before_install:
  - sudo add-apt-repository -y ppa:biometrics/bob
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev libblitz1-dev
  - pip install coveralls
install:
  - "python bootstrap.py"
  - "./bin/buildout"
script:
  - "./bin/python -c 'from bob.extension import get_config; print(get_config())'"
  - "./bin/coverage run --source=bob.extension ./bin/nosetests -sv"
  - "./bin/sphinx-build -b doctest doc sphinx"
  - "./bin/sphinx-build -b html doc sphinx"
after_success:
  - "coveralls"
