language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
env:
  global:
    - secure: S6DJMVHh6RCPSyYEEcN4B4BfD2wIn7AeDAy7Ev57Up6dtt6SdCmYFEUkxhwNOdnKXu5Rw1Kg1jOGtWCykNTv0z5042uQnHDM9QT8vwEPlrCAwEQe+VJk9aAoANQmoo6HuYXc10+9AgJSB0FaGUDoWw1jkfzBXPlmsHbFjsTeIPw=
    - secure: MkdNBK26DXTkOY41Eew3MvxLg/nSIduDlWWOe2SO20IrgPGFeptTUXXskcP9hDnJj/abuC3JDOYX1WKBy3U9MHc89+tWSQggezecety43uCcG2QQEchu3tktcBPayMxkrzSAZzjmhGKLn8CKlpFXZ1biVgjaR9o6jE9/Rvgc9iU=
before_install:
  - sudo add-apt-repository -y ppa:biometrics/bob
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev libblitz1-dev
  - pip install coveralls
install:
  - python bootstrap.py
  - ./bin/buildout
script:
  - ./bin/python -c 'from bob.extension import get_config; print(get_config())'
  - ./bin/coverage run --source=bob.extension ./bin/nosetests -sv
  - ./bin/sphinx-build -b doctest doc sphinx
  - ./bin/sphinx-build -b html doc sphinx
after_success:
  - coveralls
  - ./scripts/upload-sphinx.sh
